---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: envoy-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: frontend
    version: v1
- path: frontend-service-port-patch.yaml
  target:
    kind: Service
    name: frontend
    version: v1
- path: envoy-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: contacts
    version: v1
- path: service-port-patch.yaml
  target:
    kind: Service
    name: contacts
    version: v1
- path: envoy-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: userservice
    version: v1
- path: service-port-patch.yaml
  target:
    kind: Service
    name: userservice
    version: v1
bases:
- ./../kubernetes-manifests/
