# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
operator:
  resources:
    limits:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi
    requests:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi
  kubeletService:
    enabled: false

prometheus:
  resources:
    limits:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi
    requests:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi

exporters:
  node-exporter:
    enabled: false
  kube-state-metrics:
    enabled: false
kubelet:
  enabled: false
kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
coreDns:
  enabled: false
kubeProxy:
  enabled: false

alertmanager:
  resources:
    limits:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi
    requests:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi
  configSelector:
    matchLabels:
      alertmanagerConfig: slack

blackboxExporter:
  resources:
    limits:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi
    requests:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi
