steps:
- id: kubectl-proxy
  name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - docker run -d --net cloudbuild --name kubectl-proxy
      gcr.io/cloud-builders/gcloud compute start-iap-tunnel
      machine-dev-bastion 8888 --local-host-port 0.0.0.0:8888 --zone europe-central2-a &&
    sleep 5
- id: 'Skaffold run'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.24.0'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      gcloud container clusters get-credentials ${_CONTAINER_CLUSTER} --region ${_ZONE} --project $PROJECT_ID
      HTTPS_PROXY=kubectl-proxy:8888 skaffold run --skip-tests=true
substitutions:
    _ZONE: europe-central2-a
    _SKAFFOLD_VERSION: v1.24.0 
    _CONTAINER_CLUSTER: ${BRANCH_NAME}-cluster
timeout: 1800s