#Binauthz container build pipeline for java userservice
steps:
- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args:
  - "-c"
  - |
      echo $COMMIT_SHA
      for SERVICE in  "loadgenerator" "frontend" "userservice" "accounts-db" "accountsservice" "ledgerservice" "ledger-db"; do
        IMAGE_PATH="gcr.io/${PROJECT_ID}/$$SERVICE:${COMMIT_SHA}"
        echo "building $$IMAGE_PATH"
        docker build -t $$IMAGE_PATH src/$$SERVICE
        docker push $$IMAGE_PATH
      done
- id: "create-attestation"
  name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
  - "-c"
  - |
      for SERVICE in  "loadgenerator" "frontend" "userservice" "accounts-db" "accountsservice" "ledgerservice" "ledger-db"; do
        echo "Signing $$SERVICE"
        IMAGE_PATH="gcr.io/${PROJECT_ID}/$$SERVICE"
        IMAGE_DIGEST=`gcloud container images list-tags --format='get(digest)' $$IMAGE_PATH --limit=1`
        IMAGE_TO_ATTEST="$$IMAGE_PATH@$$IMAGE_DIGEST"
      gcloud alpha container binauthz attestations sign-and-create \
          --project="${PROJECT_ID}" \
          --artifact-url="$$IMAGE_TO_ATTEST" \
          --attestor="projects/${PROJECT_ID}/attestors/acme-finance-attestor" \
          --attestor-project="${PROJECT_ID}" \
          --keyversion-project="${PROJECT_ID}" \
          --keyversion-location="global" \
          --keyversion-keyring="my-binauthz-keyring" \
          --keyversion-key="my-binauthz-kms-key-name" \
          --keyversion="1"
      done



