steps:
- id: 'Build an application with Skaffold'
  name: eu.gcr.io/$PROJECT_ID/remote-builder
  env:
    - INSTANCE_ARGS=--image-family remote-skaffold-runner --network=${BRANCH_NAME}-vpc-network --subnet=subnet-${BRANCH_NAME}-01 --scopes=https://www.googleapis.com/auth/cloud-platform --preemptible
    - ZONE=${_ZONE}
    - USERNAME=cloud-user
    - COMMAND=gcloud container clusters get-credentials ${_CONTAINER_CLUSTER} --zone=${_ZONE} && cd /workspace && skaffold build --skip-tests=true
substitutions:
    _ZONE: europe-west3-a
    _CONTAINER_CLUSTER: ${BRANCH_NAME}-cluster
timeout: 1800s