steps:
- id: 'Skaffold run'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.24.0'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      gcloud container clusters get-credentials ${_CONTAINER_CLUSTER} --region ${_ZONE} --project $PROJECT_ID
      skaffold run
substitutions:
    _ZONE: europe-central2-a
    _SKAFFOLD_VERSION: v1.24.0 
    _CONTAINER_CLUSTER: ${BRANCH_NAME}-cluster
timeout: 1800s