steps:
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=dev-kubernetes-manifests/frontend.yaml
  - --image=gcr.io/bank-of-anthos/frontend:latest
  - --location=europe-central2-a
  - --cluster=dev-cluster
substitutions:
    _ZONE: europe-central2-a
    _SKAFFOLD_VERSION: v1.24.0 
    _CONTAINER_CLUSTER: ${BRANCH_NAME}-cluster
timeout: 1800s