steps:
- id: kubectl-proxy
  name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - docker run -d --name kubectl-proxy
      gcr.io/cloud-builders/gcloud compute start-iap-tunnel
      machine-dev-bastion 8888 --local-host-port 0.0.0.0:8888 --zone europe-central2-a &&
    docker network ls &&
    sleep 5
- id: setup-k8s
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: sh
  args:
  - -c
  - gcloud container clusters get-credentials dev-cluster --zone=europe-central2-a && HTTPS_PROXY=kubectl-proxy:8888 kubectl apply -f dev-kubernetes-manifests/config.yaml
substitutions:
    _ZONE: europe-central2-a
    _SKAFFOLD_VERSION: v1.24.0 
    _CONTAINER_CLUSTER: ${BRANCH_NAME}-cluster
timeout: 1800s