steps:
- id: remote-builder
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/remote-builder', 'src/remote-builder' ]
- name: gcr.io/$PROJECT_ID/remote-builder
  waitFor: ["remote-builder"]
  env:
    - INSTANCE_ARGS=--image-project debian-cloud --image-family debian-10 --network=dev-vpc-network --subnet=subnet-dev-01 --scopes=https://www.googleapis.com/auth/cloud-platform --preemptible
    - ZONE=${_ZONE}
    - USERNAME=cloud-user
    - COMMAND=sudo apt-get install -y docker.io && sudo docker run -v /home/cloud-user/workspace:/workspace gcr.io/k8s-skaffold/skaffold:v1.24.0 /bin/bash -c "gcloud container clusters get-credentials dev-cluster --zone=europe-central2-a && cd /workspace && skaffold run --skip-tests=true" 
images:
- 'gcr.io/$PROJECT_ID/remote-builder'
substitutions:
    _ZONE: europe-central2-a
    _SKAFFOLD_VERSION: v1.24.0 
    _CONTAINER_CLUSTER: ${BRANCH_NAME}-cluster
timeout: 1800s