apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
  - image: eu.gcr.io/pol-pod11-dev-01/frontend
    context: src/frontend
  - image: eu.gcr.io/pol-pod11-dev-01/ledgerwriter
    jib:
      project: src/ledgerwriter
  - image: eu.gcr.io/pol-pod11-dev-01/balancereader
    jib:
      project: src/balancereader
  - image: eu.gcr.io/pol-pod11-dev-01/transactionhistory
    jib:
      project: src/transactionhistory
  - image: eu.gcr.io/pol-pod11-dev-01/contacts
    context: src/contacts
  - image: eu.gcr.io/pol-pod11-dev-01/userservice
    context: src/userservice
  - image: eu.gcr.io/pol-pod11-dev-01/loadgenerator
    context: src/loadgenerator
  tagPolicy:
    sha256: {}
  googleCloudBuild:
    concurrency: 0
    timeout: 900.0s
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
    - ./extras/cloudsql/kubernetes-manifests/**.yaml