apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
  - image: gcr.io/pol-pod11-dev-01/frontend
    context: src/frontend
  - image: gcr.io/pol-pod11-dev-01/contacts
    context: src/contacts
  - image: gcr.io/pol-pod11-dev-01/userservice
    context: src/userservice
  - image: gcr.io/pol-pod11-dev-01/loadgenerator
    context: src/loadgenerator
  - image: gcr.io/pol-pod11-dev-01/accounts-db
    context: src/accounts-db
  - image: gcr.io/pol-pod11-dev-01/ledger-db
    context: src/ledger-db
  tagPolicy:
    gitCommit: {}
  googleCloudBuild:
    concurrency: 0
    timeout: 900.0s
# deploy:
#   statusCheckDeadlineSeconds: 300
#   kubectl:
#     manifests:
#     - ./dev-kubernetes-manifests/**.yaml
#     # deploy a pre-build secret
#     # in practice, this should not be checked in to source control
#     - ./extras/jwt/jwt-secret.yaml
# profiles:
#   - name: local-code
