# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_bank_of_anthos_skaffold_config_setup]
apiVersion: skaffold/v3
kind: Config
metadata:
  name: setup # module defining setup steps
manifests:
  rawYaml:
  - extras/jwt/jwt-secret.yaml
  - dev-kubernetes-manifests/config.yaml
deploy:
  kubectl: {}
# [END gke_bank_of_anthos_skaffold_config_setup]
---
# [START gke_bank_of_anthos_skaffold_config_db]
apiVersion: skaffold/v3
kind: Config
metadata:
  name: db # module defining database deployments
requires:
- configs:
  - setup
build:
  artifacts:
  - image: accounts-db
    context: src/accounts-db
  - image: ledger-db
    context: src/ledger-db
manifests:
  rawYaml:
  - dev-kubernetes-manifests/accounts-db.yaml
  - dev-kubernetes-manifests/ledger-db.yaml
deploy:
  kubectl: {}
# [END gke_bank_of_anthos_skaffold_config_db]
---
# [START gke_bank_of_anthos_skaffold_config_backend]
apiVersion: skaffold/v3
kind: Config
metadata:
  name: backend # module defining backend services
requires:
- configs:
  - db
build:
  artifacts:
  - image: ledgerwriter
    jib:
      project: src/ledgerwriter
  - image: balancereader
    jib:
      project: src/balancereader
  - image: transactionhistory
    jib:
      project: src/transactionhistory
  - image: contacts
    context: src/contacts
  - image: userservice
    context: src/userservice
manifests:
  rawYaml:
  - dev-kubernetes-manifests/balance-reader.yaml
  - dev-kubernetes-manifests/contacts.yaml
  - dev-kubernetes-manifests/ledger-writer.yaml
  - dev-kubernetes-manifests/transaction-history.yaml
  - dev-kubernetes-manifests/userservice.yaml
deploy:
  kubectl: {}
# [END gke_bank_of_anthos_skaffold_config_backend]
---
# [START gke_bank_of_anthos_skaffold_config_frontend]
apiVersion: skaffold/v3
kind: Config
metadata:
  name: frontend # module defining frontend service
build:
  artifacts:
  - image: frontend
    context: src/frontend
manifests:
  rawYaml:
  - dev-kubernetes-manifests/frontend.yaml
deploy:
  kubectl: {}
# [END gke_bank_of_anthos_skaffold_config_frontend]
---
# [START gke_bank_of_anthos_skaffold_config_loadgenerator]
apiVersion: skaffold/v3
kind: Config
metadata:
  name: loadgenerator # module defining a load generator service
build:
  artifacts:
  - image: loadgenerator
    context: src/loadgenerator
manifests:
  rawYaml:
  - dev-kubernetes-manifests/loadgenerator.yaml
deploy:
  kubectl: {}
# [END gke_bank_of_anthos_skaffold_config_loadgenerator]