{{- if .Values.userService.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: {{ .Values.userService.team }}
    tier: {{ .Values.userService.tier }}
  name: userservice
spec:
  ports:
    - name: http
      port: {{ .Values.userService.service.port }}
      targetPort: {{ .Values.userService.service.port }}
  selector:
    app: userservice
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: {{ .Values.userService.team }}
    tier: {{ .Values.userService.tier }}
  type: {{ .Values.userService.service.type }}
{{- end }}
