{{- if .Values.balanceReader.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: {{ .Values.balanceReader.team }}
    tier: {{ .Values.balanceReader.tier }}
  name: balancereader
spec:
  ports:
    - name: http
      port: {{ .Values.balanceReader.service.port }}
      targetPort: {{ .Values.balanceReader.service.port }}
  selector:
    app: balancereader
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: {{ .Values.balanceReader.team }}
    tier: {{ .Values.balanceReader.tier }}
  type: {{ .Values.balanceReader.service.type }}
{{- end }}
