apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: bank-address
    networking.gke.io/managed-certificates: bank-ssl-certificate
spec:
  backend:
    serviceName: frontend-nodeport
    servicePort: 80