---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: bank-of-anthos
    environment: development
    team: ledger
    tier: db
  name: ledger-db
spec:
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432
  selector:
    app: ledger-db
    application: bank-of-anthos
    environment: development
    team: ledger
    tier: db
  type: ClusterIP
