# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_gateway_pb2 as agent__gateway__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentGatewayStub(object):
    """The agent gateway service definition, now supporting a two-step workflow.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProposeAction = channel.unary_unary(
                '/portfolioagent.AgentGateway/ProposeAction',
                request_serializer=agent__gateway__pb2.ProposeActionRequest.SerializeToString,
                response_deserializer=agent__gateway__pb2.ProposeActionResponse.FromString,
                _registered_method=True)
        self.ConfirmAction = channel.unary_unary(
                '/portfolioagent.AgentGateway/ConfirmAction',
                request_serializer=agent__gateway__pb2.ConfirmActionRequest.SerializeToString,
                response_deserializer=agent__gateway__pb2.ConfirmActionResponse.FromString,
                _registered_method=True)


class AgentGatewayServicer(object):
    """The agent gateway service definition, now supporting a two-step workflow.
    """

    def ProposeAction(self, request, context):
        """Step 1: Propose a financial action based on a user query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmAction(self, request, context):
        """Step 2: Execute a previously proposed action after user confirmation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProposeAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeAction,
                    request_deserializer=agent__gateway__pb2.ProposeActionRequest.FromString,
                    response_serializer=agent__gateway__pb2.ProposeActionResponse.SerializeToString,
            ),
            'ConfirmAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmAction,
                    request_deserializer=agent__gateway__pb2.ConfirmActionRequest.FromString,
                    response_serializer=agent__gateway__pb2.ConfirmActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'portfolioagent.AgentGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('portfolioagent.AgentGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentGateway(object):
    """The agent gateway service definition, now supporting a two-step workflow.
    """

    @staticmethod
    def ProposeAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portfolioagent.AgentGateway/ProposeAction',
            agent__gateway__pb2.ProposeActionRequest.SerializeToString,
            agent__gateway__pb2.ProposeActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portfolioagent.AgentGateway/ConfirmAction',
            agent__gateway__pb2.ConfirmActionRequest.SerializeToString,
            agent__gateway__pb2.ConfirmActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
