# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61gent_gateway.proto\x12\x0eportfolioagent\";\n\x14ProposeActionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nquery_text\x18\x02 \x01(\t\"q\n\x15ProposeActionResponse\x12\x11\n\taction_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65xplanation\x18\x02 \x01(\t\x12\x18\n\x10proposed_changes\x18\x03 \x03(\t\x12\x16\n\x0estatus_message\x18\x04 \x01(\t\":\n\x14\x43onfirmActionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\taction_id\x18\x02 \x01(\t\"H\n\x15\x43onfirmActionResponse\x12\x17\n\x0f\x63onfirmation_id\x18\x01 \x01(\t\x12\x16\n\x0estatus_message\x18\x02 \x01(\t2\xce\x01\n\x0c\x41gentGateway\x12^\n\rProposeAction\x12$.portfolioagent.ProposeActionRequest\x1a%.portfolioagent.ProposeActionResponse\"\x00\x12^\n\rConfirmAction\x12$.portfolioagent.ConfirmActionRequest\x1a%.portfolioagent.ConfirmActionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROPOSEACTIONREQUEST']._serialized_start=39
  _globals['_PROPOSEACTIONREQUEST']._serialized_end=98
  _globals['_PROPOSEACTIONRESPONSE']._serialized_start=100
  _globals['_PROPOSEACTIONRESPONSE']._serialized_end=213
  _globals['_CONFIRMACTIONREQUEST']._serialized_start=215
  _globals['_CONFIRMACTIONREQUEST']._serialized_end=273
  _globals['_CONFIRMACTIONRESPONSE']._serialized_start=275
  _globals['_CONFIRMACTIONRESPONSE']._serialized_end=347
  _globals['_AGENTGATEWAY']._serialized_start=350
  _globals['_AGENTGATEWAY']._serialized_end=556
# @@protoc_insertion_point(module_scope)
