# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61gent_gateway.proto\x12\x0eportfolioagent\"3\n\x0c\x41gentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nquery_text\x18\x02 \x01(\t\"&\n\rAgentResponse\x12\x15\n\rresponse_text\x18\x01 \x01(\t2_\n\x0c\x41gentGateway\x12O\n\x0eProcessRequest\x12\x1c.portfolioagent.AgentRequest\x1a\x1d.portfolioagent.AgentResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTREQUEST']._serialized_start=39
  _globals['_AGENTREQUEST']._serialized_end=90
  _globals['_AGENTRESPONSE']._serialized_start=92
  _globals['_AGENTRESPONSE']._serialized_end=130
  _globals['_AGENTGATEWAY']._serialized_start=132
  _globals['_AGENTGATEWAY']._serialized_end=227
# @@protoc_insertion_point(module_scope)
