# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_tls_domain_managedcerts_managed_certificates_managedcertificate_bank_ssl_certificate]
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: bank-ssl-certificate
spec:
  domains:
    - bank-of-anthos.xyz  # repace me with DNS name mapped to bank-address
# [END gke_tls_domain_managedcerts_managed_certificates_managedcertificate_bank_ssl_certificate]
---
# [START gke_tls_domain_managedcerts_managed_certificates_service_frontend_nodeport]
apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
# [END gke_tls_domain_managedcerts_managed_certificates_service_frontend_nodeport]
---
# [START gke_tls_domain_managedcerts_managed_certificates_ingress_frontend_ingress]
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: bank-address # create me with `gcloud compute addresses create bank-address --global`
    networking.gke.io/managed-certificates: bank-ssl-certificate
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: frontend-nodeport
    servicePort: 8080
# [END gke_tls_domain_managedcerts_managed_certificates_ingress_frontend_ingress]