apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ledgermonolith
  description: Monolithic Ledger Service for Bank of Anthos
  tags:
    - java
    - backend
  links:
    - url: https://github.com/googlecloudplatform/bank-of-anthos
      title: Bank of Anthos - Upstream repo
      icon: help
  annotations:
    'backstage.io/kubernetes-id': ledgermonolith
    'backstage.io/techdocs-ref': dir:../src/ledgermonolith
spec:
  type: service
  lifecycle: experimental
  owner: group:default/cpet-core
  system: bank-of-anthos
  subcomponentof:
    - system:bank-of-anthos
  # dependsOn: ['component:artists-db']
  # apiConsumedBy: ['component:frontend']