apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bank-loadgenerator
  description: Load Generator for Bank of Anthos
  tags:
    - python
  links:
    - url: https://github.com/googlecloudplatform/bank-of-anthos
      title: Bank of Anthos - Upstream repo
      icon: help
  annotations:
    'backstage.io/kubernetes-id': bank-loadgenerator
    'backstage.io/techdocs-ref': dir:../src/loadgenerator
spec:
  type: service
  lifecycle: experimental
  owner: group:default/cpet-core
  system: bank-of-anthos
  subcomponentof:
    - system:bank-of-anthos
  # dependsOn: ['component:artists-db']
  # apiConsumedBy: ['component:frontend']