apiVersion: v1
data:
  ACCOUNTS_DB_URI: postgresql://admin:admin@127.0.0.1:5432/accounts-db
  POSTGRES_DB: accounts-db
  POSTGRES_PASSWORD: admin
  POSTGRES_USER: admin
kind: ConfigMap
metadata:
  labels:
    app: accounts-db
    application: bank-of-splunk
    environment: production
    team: accounts
    tier: db
  name: accounts-db-config
  namespace: bank-of-anthos-production
