apiVersion: v1
data:
  POSTGRES_DB: postgresdb
  POSTGRES_PASSWORD: password
  POSTGRES_USER: admin
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-db:5432/postgresdb
  SPRING_DATASOURCE_USERNAME: admin
kind: ConfigMap
metadata:
  labels:
    app: ledger-db
    application: bank-of-splunk
    environment: development
    team: ledger
    tier: db
  name: ledger-db-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: bank-of-splunk
    environment: development
    team: ledger
    tier: db
  name: ledger-db
spec:
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432
  selector:
    app: ledger-db
    application: bank-of-splunk
    environment: development
    team: ledger
    tier: db
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    application: bank-of-splunk
    environment: development
    team: ledger
    tier: db
  name: ledger-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-db
      application: bank-of-splunk
      environment: development
      team: ledger
      tier: db
  serviceName: ledger-db
  template:
    metadata:
      labels:
        app: ledger-db
        application: bank-of-splunk
        environment: development
        team: ledger
        tier: db
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: ledger-db-config
            - configMapRef:
                name: demo-data-config
          image: ghcr.io/splunk/bank-of-splunk/ledger-db:v1.3.1@sha256:de1ae1694d03c6c368245ec88ca016476dffa1f73a5d6cd67ab949a96c93d668
          name: postgres
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
              subPath: postgres
      serviceAccount: bank-of-anthos
      serviceAccountName: default
      volumes:
        - emptyDir: {}
          name: postgresdb
