apiVersion: v1
data:
  POSTGRES_DB: ledger-db
  POSTGRES_PASSWORD: admin
  POSTGRES_USER: admin
  SPRING_DATASOURCE_PASSWORD: admin
  SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/ledger-db
  SPRING_DATASOURCE_USERNAME: admin
kind: ConfigMap
metadata:
  labels:
    app: ledger-db
    application: bank-of-splunk
    environment: production
    team: ledger
    tier: db
  name: ledger-db-config
  namespace: bank-of-anthos-production
