apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ledgerwriter
spec:
  maxReplicas: 7
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ledgerwriter
