apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: transactionhistory
spec:
  maxReplicas: 7
  minReplicas: 2
  targetCPUUtilizationPercentage: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transactionhistory
