
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: userservice
spec:
  maxReplicas: 20
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userservice
