{{- if .Values.transactionHistory.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: {{ .Values.transactionHistory.team }}
    tier: {{ .Values.transactionHistory.tier }}
  name: transactionhistory
spec:
  ports:
    - name: http
      port: {{ .Values.transactionHistory.service.port }}
      targetPort: {{ .Values.transactionHistory.service.port }}
  selector:
    app: transactionhistory
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: {{ .Values.transactionHistory.team }}
    tier: {{ .Values.transactionHistory.tier }}
  type: {{ .Values.transactionHistory.service.type }}
{{- end }}
