apiVersion: v1
kind: Service
metadata:
  labels:
    application: bank-of-anthos
    environment: development
    team: accounts
    tier: backend
  name: contacts
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: contacts
    application: bank-of-anthos
    environment: development
    team: accounts
    tier: backend
  type: ClusterIP
