{{- if .Values.ledgerDb.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: {{ .Values.ledgerDb.team }}
    tier: {{ .Values.ledgerDb.tier }}
  name: ledger-db
spec:
  ports:
    - name: tcp
      port: {{ .Values.ledgerDb.service.port }}
      targetPort: {{ .Values.ledgerDb.service.port }}
  selector:
    app: ledger-db
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: {{ .Values.ledgerDb.team }}
    tier: {{ .Values.ledgerDb.tier }}
  type: {{ .Values.ledgerDb.service.type }}
{{- end }}
