sonar.projectKey=mohdtarique_bank-of-anthos-frontend
sonar.organization=boa-sonar-token

sonar.sources=.
sonar.exclusions=**/*.html,**/*.css,**/*.js,**/static/**,**/templates/**
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8