sonar.projectKey=bank-of-anthos-frontend-project-key
sonar.organization=graycasterinc

sonar.sources=.
sonar.exclusions=tests/**,**/*.html,**/*.css,**/*.js
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
