{{- if .Values.loadGenerator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: loadgenerator
    tier: test
  name: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
      application: {{ .Values.global.application }}
      environment: {{ .Values.global.environment }}
      team: loadgenerator
      tier: test
  template:
    metadata:
      annotations:
        {{- if .Values.istio.enabled }}
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        {{- end }}
      labels:
        app: loadgenerator
        application: {{ .Values.global.application }}
        environment: {{ .Values.global.environment }}
        team: loadgenerator
        tier: test
    spec:
      containers:
        - env:
            - name: FRONTEND_ADDR
              value: {{ .Values.loadGenerator.env.frontendAddr | quote }}
            - name: USERS
              value: {{ .Values.loadGenerator.env.users | quote }}
            {{- if .Values.loadGenerator.env.duration }}
            - name: DURATION
              value: {{ .Values.loadGenerator.env.duration | quote }}
            {{- end }}
            - name: LOG_LEVEL
              value: error
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.loadGenerator.image.repository }}:{{ .Values.loadGenerator.image.tag | default .Values.global.version }}"
          name: loadgenerator
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
      restartPolicy: Always
      securityContext:
        {{- toYaml .Values.global.securityContext | nindent 8 }}
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      terminationGracePeriodSeconds: 5
{{- end }}
