apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: frontend-global-ingress
spec:
  template:
    spec:
      backend:
        serviceName: frontend-mcs
        servicePort: 8080