{{- if .Values.ledgerWriter.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: {{ .Values.ledgerWriter.team }}
    tier: {{ .Values.ledgerWriter.tier }}
  name: ledgerwriter
spec:
  ports:
    - name: http
      port: {{ .Values.ledgerWriter.service.port }}
      targetPort: {{ .Values.ledgerWriter.service.port }}
  selector:
    app: ledgerwriter
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: {{ .Values.ledgerWriter.team }}
    tier: {{ .Values.ledgerWriter.tier }}
  type: {{ .Values.ledgerWriter.service.type }}
{{- end }}
