{
 "title": "Application components blue",
 "time": { "from": "now-90m", "to": "now" },
 "panels": [
  {
   "title": "Contacts - Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{kubernetes_pod_name=~\"contacts.+\",envoy_response_code_class=~\"2|3\"}[5m]))",
     "legendFormat": "total 2XX|3XX requests/s"
    }
   ]
  },
  {
   "title": "Contacts - Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(envoy_cluster_external_upstream_rq_xx{kubernetes_pod_name=~\"contacts.+\",envoy_response_code_class=~\"4|5\"}[5m]))",
     "legendFormat": "4XX|5XX errors/s"
    }
   ]
  },
  {
   "title": "Contacts - Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5,rate(envoy_cluster_upstream_rq_time_bucket{kubernetes_pod_name=~\"contacts.+\"}[3m])))",
     "legendFormat": "transaction latency ms"
    }
   ]
  },
  {
   "title": "Contacts - Node Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_total{kubernetes_pod_name=~\"contacts.+\"})",
     "legendFormat": "active pods"
    }
   ]
  },
  {
   "title": "Frontend - Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{kubernetes_pod_name=~\"frontend.+\",envoy_response_code_class=~\"2|3\"}[5m]))",
     "legendFormat": "total 2XX|3XX requests/s"
    }
   ]
  },
  {
   "title": "Frontend - Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(envoy_cluster_external_upstream_rq_xx{kubernetes_pod_name=~\"frontend.+\",envoy_response_code_class=~\"4|5\"}[5m]))",
     "legendFormat": "4XX|5XX errors/sec"
    }
   ]
  },
  {
   "title": "Frontend - Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5,rate(envoy_cluster_upstream_rq_time_bucket{kubernetes_pod_name=~\"frontend.+\"}[3m])))",
     "legendFormat": "transaction latency ms"
    }
   ]
  },
  {
   "title": "Frontend - Node Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_total{kubernetes_pod_name=~\"frontend.+\"})",
     "legendFormat": "active pods"
    }
   ]
  },
  {
   "title": "Userservice - Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{kubernetes_pod_name=~\"userservice.+\",envoy_response_code_class=~\"2|3\"}[5m]))",
     "legendFormat": "total 2XX|3XX requests/s"
    }
   ]
  },
  {
   "title": "UserService - Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "avg(rate(envoy_cluster_external_upstream_rq_xx{kubernetes_pod_name=~\"userservice.+\",envoy_response_code_class=~\"4|5\"}[5m]))",
     "legendFormat": "4XX|5XX error/s"
    }
   ]
  },
  {
   "title": "Userservice - Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5,rate(envoy_cluster_upstream_rq_time_bucket{kubernetes_pod_name=~\"userservice.+\"}[3m])))",
     "legendFormat": "transaction latency ms"
    }
   ]
  },
  {
   "title": "Userservice - Node Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_total{kubernetes_pod_name=~\"userservice.+\"})",
     "legendFormat": "active pods"
    }
   ]
  }
 ]
}