{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: frontend
    tier: web
  name: frontend
spec:
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: frontend
    application: {{ .Values.global.application }}
    environment: {{ .Values.global.environment }}
    team: frontend
    tier: web
  type: {{ .Values.frontend.service.type }}
{{- end }}
