name: ci-frontend
run-name: ${{ github.actor }} is testing GitHub Actions
on: 
  push:
    branches: [main]
    paths:
      - "src/frontend/**"
      - ".github/workflows/ci-frontend.yml"

  pull_request:
    branches: [main]
    paths:
      - "src/frontend/**"

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    outputs:
      image_tag: "test-image-tag"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: ls ${{ github.workspace }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.12"
          cache: "pip"
          cache-dependancy-path: src/frontend/requirements.txt

      - name: Intall dependancy
        run: | 
          pip install -r src/frontend/requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          flake8 src/frontend/ \
            --max-line-length=120 \
            --exclude=__pycache__,.git \
            --count --statistics
        continue-on-error: true
      
      - name: Run unit test
        run: |
          if [ -d "src/frontend/tests"]; then
            pytest src/frontend/tests \
              -v \
              --tb=short
          else
            echo "No tests directory found - skipping"
          fi

      - name: Setup Docker Builx
        uses: docker/setup-buildx-action@v3

