name: Deploy Bank of Anthos to GKE (Complete Recreation)

on:
  workflow_dispatch:  # Manual trigger only for safety
  push:
    branches:
      - recreate-deploy  # Only trigger on specific branch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: bank-of-anthos
  GKE_ZONE: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

    - name: Delete existing deployments (Complete Recreation)
      run: |
        echo "⚠️  WARNING: This will delete all existing deployments!"
        echo "Deleting existing Bank of Anthos resources..."
        
        # Delete deployments (this will terminate all pods)
        kubectl delete deployment frontend userservice contacts ledgerwriter balancereader transactionhistory loadgenerator --ignore-not-found=true
        
        # Delete services
        kubectl delete service frontend userservice contacts ledgerwriter balancereader transactionhistory accounts-db ledger-db --ignore-not-found=true
        
        # Delete configmaps and secrets (except JWT secret)
        kubectl delete configmap config --ignore-not-found=true
        
        # Wait for resources to be deleted
        echo "Waiting for resources to be deleted..."
        sleep 30

    - name: Deploy JWT Secret
      run: kubectl apply -f ./extras/jwt/jwt-secret.yaml

    - name: Deploy Bank of Anthos (Fresh Installation)
      run: |
        echo "Deploying fresh Bank of Anthos installation..."
        kubectl apply -f ./kubernetes-manifests

    - name: Wait for deployment to complete
      run: |
        echo "Waiting for fresh deployment to complete..."
        kubectl rollout status deployment/frontend --timeout=300s
        kubectl rollout status deployment/userservice --timeout=300s
        kubectl rollout status deployment/contacts --timeout=300s
        kubectl rollout status deployment/ledgerwriter --timeout=300s
        kubectl rollout status deployment/balancereader --timeout=300s
        kubectl rollout status deployment/transactionhistory --timeout=300s
        kubectl rollout status deployment/loadgenerator --timeout=300s
        echo "✅ Fresh deployment completed successfully!"

    - name: Verify deployment
      run: |
        echo "=== Pod Status ==="
        kubectl get pods
        echo ""
        echo "=== Service Status ==="
        kubectl get services
        echo ""
        echo "=== Frontend Service Details ==="
        kubectl get service frontend
        echo ""
        echo "🎉 Fresh deployment completed! Use the EXTERNAL-IP above to access the application."
