name: Test GCP Authentication

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: bank-of-anthos
  GKE_ZONE: us-central1

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Test Authentication
      run: |
        echo "Testing authentication..."
        gcloud auth list
        gcloud config list
        gcloud projects describe ${{ env.PROJECT_ID }}

    - name: Test GKE Access
      run: |
        echo "Testing GKE access..."
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}
        kubectl get nodes
